#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Jangada: regenerate the web editor mock's parameter tables from the firmware.

  tools/gen_editor_tables.py          rewrite the generated block of web/editor.html
  tools/gen_editor_tables.py --check  exit 1 if it is not up to date (tests/run_tests.sh, CI)

Builds tools/dump_editor_tables.c on the host (needs build/gen, as the host tests do) and puts its
output between the "<generated ...>" and "</generated>" markers of the mock device."""
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "web" / "editor.html"
BEGIN = "  /* <generated by tools/gen_editor_tables.py"
END = "  /* </generated> */\n"


def tables():
    cc = os.environ.get("CC", "cc").split()
    with tempfile.TemporaryDirectory() as d:
        exe = Path(d) / "dump"
        subprocess.run([*cc, "-O1", "-w", f"-I{ROOT}/build/gen", f"-I{ROOT}/firmware/src", "-o", str(exe),
                        str(ROOT / "tools" / "dump_editor_tables.c"), "-lm"], check=True)
        return subprocess.run([str(exe)], check=True, capture_output=True, text=True).stdout


def main():
    html = HTML.read_text()
    a = html.find(BEGIN)
    b = html.find(END, a)
    if a < 0 or b < 0:
        raise SystemExit("web/editor.html: no generated block (markers missing)")
    out = tables()
    new = html[:a] + out + html[b + len(END):]
    if "--check" in sys.argv:
        if new != html:
            print("web/editor.html: the mock's tables differ from the firmware: run tools/gen_editor_tables.py")
            sys.exit(1)
        import re
        c = dict(re.findall(r"(P_COUNT|G_COUNT|P_E0) = (\d+)", out))
        want = f"const EXPECT = {{ pcount: {c['P_COUNT']}, gcount: {c['G_COUNT']}, pe0: {c['P_E0']} }};"
        if want not in html:
            print(f"web/editor.html: the editor's layout expects another firmware: want '{want}'")
            sys.exit(1)
        print("editor mock tables == firmware tables  ok")
        return
    HTML.write_text(new)
    print("web/editor.html: generated block rewritten")


if __name__ == "__main__":
    main()
